services:
  db:
    image: postgres:15
    container_name: fbr_db
    restart: always
    environment:
      POSTGRES_DB: fbr_di_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fbr_secure_2026
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fbr_network
  backend:
    build: ./backend
    container_name: fbr_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:fbr_secure_2026@db:5432/fbr_di_db
    restart: always
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - fbr_network
  frontend:
    build: ./frontend
    container_name: fbr_frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fbr_network
volumes:
  postgres_data:
networks:
  fbr_network:
