"""fresh initial schema

Revision ID: cc2c7c7282a8
Revises: 
Create Date: 2026-01-19 19:24:45.488682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2c7c7282a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sellerNTNCNIC', sa.String(length=20), nullable=False),
    sa.Column('sellerBusinessName', sa.String(length=100), nullable=False),
    sa.Column('sellerProvince', sa.String(length=50), nullable=False),
    sa.Column('sellerAddress', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('reference_cache',
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('endpoint')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoiceRefNo', sa.String(length=100), nullable=True),
    sa.Column('fbrInvoiceNo', sa.String(length=100), nullable=True),
    sa.Column('invoiceType', sa.String(length=50), nullable=False),
    sa.Column('invoiceDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sellerNTNCNIC', sa.String(length=20), nullable=False),
    sa.Column('sellerBusinessName', sa.String(length=100), nullable=False),
    sa.Column('sellerProvince', sa.String(length=50), nullable=False),
    sa.Column('sellerAddress', sa.String(length=200), nullable=False),
    sa.Column('buyerNTNCNIC', sa.String(length=20), nullable=True),
    sa.Column('buyerBusinessName', sa.String(length=100), nullable=False),
    sa.Column('buyerProvince', sa.String(length=50), nullable=False),
    sa.Column('buyerAddress', sa.String(length=200), nullable=False),
    sa.Column('buyerRegistrationType', sa.String(length=20), nullable=False),
    sa.Column('scenarioId', sa.String(length=10), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('printed_count', sa.Integer(), nullable=True),
    sa.Column('last_printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_fbrInvoiceNo'), 'invoices', ['fbrInvoiceNo'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoiceRefNo'), 'invoices', ['invoiceRefNo'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('hsCode', sa.String(length=20), nullable=False),
    sa.Column('productDescription', sa.Text(), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('rate', sa.String(length=10), nullable=False),
    sa.Column('valueSalesExcludingST', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('salesTaxApplicable', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('totalValues', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fixedNotifiedValueOrRetailPrice', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('salesTaxWithheldAtSource', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('furtherTax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('extraTax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fedPayable', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sroScheduleNo', sa.String(length=50), nullable=True),
    sa.Column('sroItemSerialNo', sa.String(length=50), nullable=True),
    sa.Column('saleType', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_invoiceRefNo'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_fbrInvoiceNo'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('reference_cache')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
